# Chapter 10: Exceptions
------------------------------------------------------------------------
## Overview Chapter 10
* Exceptions
* `try` statement
* `catch` statement
* `finally` statement
* `throw` statement
* "rethrow" vs "throw"

------------------------------------------------------------------------
## Exceptions
* Failure during program execution
* An "exceptional event"
* An "exception" can be typed

------------------------------------------------------------------------
### Some bad examples

#### `FormatException`
```csharp
int.Parse("abc");
```

#### `OverflowException`
```csharp
int.Parse("12345678901234567890");
```

#### `ArgumentNullException`
```csharp
int.Parse(null);
```

#### `DivisionByZeroException`
```csharp
int divisor = Random.Shared.Next(0, 0); // Always 0
int result = 999 / divisor;
```

notes:
- Demo in scratch project

***********************************************************************
## Try...Catch...Finally
* Statement
* Used to execute a block of code
* Always followed by either a `catch` or `finally` statement

------------------------------------------------------------------------
### Try: Syntax
```csharp
// â”Œ keyword
   try
   {
       // statement block
   }
   catch
   {
       // statement block
   }
   finally
   {
       // statement block
   }
```

------------------------------------------------------------------------
### Try: Example
```csharp
int number = 0;
Console.Write("Enter a number: ");
try
{
    var text = Console.ReadLine();
    return int.Parse(text);
}
catch 
{ 
    Console.WriteLine("Please enter a valid number");
}
```

***********************************************************************
## Catch
------------------------------------------------------------------------
### Catch: Syntax
- Has to be used after a `try` statement
- Can be used multiple times